### ISSUE TITLE
Not honoring .svgo.yml

### ISSUE THREAD

**Issue by ronilaukkarinen** [1000ch/vscode-svgo#15]
I have `removeViewBox: false` in my .svgo.yml but this plugin still removes viewBox attribute.

Full .svgo.yml in my workspace root directory:

```
multipass: true
full: true
plugins:
  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: true
  - removeXMLNS: true
  - removeEditorsNSData: true
  - cleanupAttrs: true
  - inlineStyles: true
  - minifyStyles: true
  - convertStyleToAttrs: true
  - cleanupIDs: true
  - prefixIds: true
  - removeRasterImages: true
  - removeUselessDefs: true
  - cleanupNumericValues: true
  - cleanupListOfValues: true
  - convertColors: true
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeViewBox: false
  - cleanupEnableBackground: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - convertShapeToPath: true
  - convertEllipseToCircle: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: true
  - convertPathData: true
  - convertTransform: true
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - mergePaths: true
  - removeUnusedNS: true
  - sortAttrs: true
  - sortDefsChildren: true
  - removeTitle: true
  - removeDesc: true
  - removeDimensions: false
  - removeAttrs: true
  - removeAttributesBySelector: true
  - removeElementsByAttr: true
  - addClassesToSVGElement: true
  - removeStyleElement: true
  - removeScriptElement: true
  - addAttributesToSVGElement: true
  - removeOffCanvasPaths: true
  - reusePaths: true
```
